allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

//rootProject.buildDir = '../build'
//subprojects {
//    project.buildDir = "${rootProject.buildDir}/${project.name}"
//}
subprojects {
    project.evaluationDependsOn(':app')
}
//
//subprojects { subproject ->
//    afterEvaluate {
//        if (subproject.hasProperty('android')) {
//            android {
//                if (namespace == null) {
//                    def manifest = file("${subproject.projectDir}/src/main/AndroidManifest.xml")
//                    if (manifest.exists()) {
//                        def packageName = new XmlParser().parse(manifest).attribute('package')
//                        if (packageName != null) {
//                            namespace packageName
//                        }
//                    }
//                }
//            }
//        }
//    }
//}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
